name: Publish Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Nightly
        run: wget https://buildbot.libretro.com/nightly/apple/ios-arm64/RetroArch.ipa
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release
          files: RetroArch.ipa
          body_path: libretro/RetroArch-CHANGES.md
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: WhyIsCronTaken/retroarch-source
